[project]
name = "knowledge_graph_tools"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv",
    "neo4j",
    "click",
    "pygithub",
    "pandas",
    "yfiles-jupyter-graphs-for-neo4j>=2.0.0",
    "ipykernel>=7.3.0",
    "yfiles-jupyter-graphs>=2.0.0",
    "ipywidgets>=8.1.9",
    "jupyterlab>=4.6.3",
]

[project.scripts]
kgtools = "codebase_kg.cli.cli:cli"

[dependency-groups]
dev = ["flake8"]

[tool.uv]
package = true
default-groups = "all"


[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.setuptools.packages.find]
where = ["src"]
